const FETCH_INIT: string = "FETCH_INIT"
const FETCH_SUCCESS: string = "FETCH_SUCCESS"
const FETCH_FAILURE: string = "FETCH_FAILURE"

// functions
const TIME_SERIES_INTRADAY_EXTENDED = 'TIME_SERIES_INTRADAY_EXTENDED'
const TIME_SERIES_INTRADAY = 'TIME_SERIES_INTRADAY'
const DIGITAL_CURRENCY_DAILY = 'DIGITAL_CURRENCY_DAILY'

// interval types
const DAILY_INTERVAL_ADJUSTED_KEY = 'Time Series (Daily)'
const INTRADAY_INTERVAL_KEY = 'Time Series (15min)'
const DIGITAL_CURRENCY_INTERVAL_KEY = "Time Series (Digital Currency Daily)"

export {
  FETCH_INIT,
  FETCH_SUCCESS,
  FETCH_FAILURE,
  TIME_SERIES_INTRADAY_EXTENDED,
  TIME_SERIES_INTRADAY,
  DIGITAL_CURRENCY_DAILY,
  DAILY_INTERVAL_ADJUSTED_KEY,
  INTRADAY_INTERVAL_KEY,
  DIGITAL_CURRENCY_INTERVAL_KEY
}