const FETCH_INIT = "FETCH_INIT"
const FETCH_SUCCESS = "FETCH_SUCCESS"
const FETCH_FAILURE = "FETCH_FAILURE"

// functions
const OVERVIEW = "OVERVIEW"
const TIME_SERIES_MONTHLY_ADJUSTED = "TIME_SERIES_MONTHLY_ADJUSTED"
const TIME_SERIES_INTRADAY = "TIME_SERIES_INTRADAY"
const DIGITAL_CURRENCY_DAILY = "DIGITAL_CURRENCY_DAILY"

// interval types
const MONTHLY_INTERVAL_ADJUSTED_KEY = "Monthly Adjusted Time Series"
const INTRADAY_INTERVAL_KEY = "Time Series (15min)"
const DIGITAL_CURRENCY_INTERVAL_KEY = "Time Series (Digital Currency Daily)"

// news
const NEWS_SENTIMENT = "NEWS_SENTIMENT"

export {
  FETCH_INIT,
  FETCH_SUCCESS,
  FETCH_FAILURE,
  TIME_SERIES_MONTHLY_ADJUSTED,
  TIME_SERIES_INTRADAY,
  DIGITAL_CURRENCY_DAILY,
  MONTHLY_INTERVAL_ADJUSTED_KEY,
  INTRADAY_INTERVAL_KEY,
  DIGITAL_CURRENCY_INTERVAL_KEY,
  NEWS_SENTIMENT,
  OVERVIEW
}